DATE_COLUMN_NUMBER = 1
TITLE_COLUMN_NUMBER = 2
TEXT_COLUMN_NUMBER = 3
FORMULAE_COLUMN_NUMBER = 5
ID_COLUMN_NUMBER = 6

DATE_COLUMN = 'A'
TITLE_COLUMN = 'B'
TEXT_COLUMN = 'C'
DEADLINE_COLUMN = 'D'
FORMULAE_COLUMN = 'E'
ID_COLUMN = 'F'
OK_COLUMN = 'G'

